name: Run tests

on:
  push:
    branches:
      - '*'

jobs:
  run_tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: lint
        run: black . --check

      - name: type-check
        run: mypy .

      - name: test with pytest
        run: pytest -x *_test.py